version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dvm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    image: my_dj_app
    ports:
      - 8000:8000
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ayushgupta@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
